go: &go
  image: golang
  working_dir: /go/migrate
  volumes:
    - $PWD:/go/migrate
go-test:
  <<: *go
  command: sh -c 'go get -t -v ./... && go test -p=1 -v ./...'
  links:
    - postgres
    - mysql
    - cassandra
    - crate
go-build:
  <<: *go
  command: sh -c 'go get -v && go build -ldflags ''-s'' -o migrater'
  environment:
    CGO_ENABLED: 1
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: migrate
mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_DATABASE: migratetest
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
cassandra:
  image: cassandra:2.2
  volumes:
    - "./drivers/cassandra-driver/cassandra-init.sh:/cassandra-init.sh"
  command: "sh /cassandra-init.sh"
crate:
  image: crate
