language: go
sudo: required

go:
  - "1.11"
  - "1.12"
  - "1.13"

services:
  - docker

before_install:
  - sed -i -e 's/golang/golang:'"$TRAVIS_GO_VERSION"'/' docker-compose.yml

install:
  - go get -t -v github.com/db-journey/postgresql-driver

script: make test
