go: &go
  image: golang
  working_dir: /go/src/github.com/db-journey/postgresql-driver
  volumes:
    - $GOPATH:/go
go-test:
  <<: *go
  command: sh -c 'go get -t -v ./... && go test -p=1 -v ./...'
  links:
    - postgres
postgres:
  image: postgres
