go: &go
  image: golang
  working_dir: /go/src/github.com/db-journey/cassandra-driver
  volumes:
    - $GOPATH:/go
go-test:
  <<: *go
  command: sh -c 'go get -t -v ./... && go test -p=1 -v ./...'
  links:
    - cassandra
go-build:
  <<: *go
  command: sh -c 'go get -v && go build -ldflags ''-s'' -o migrater'
  environment:
    CGO_ENABLED: 1
cassandra:
  image: cassandra:2.2
